### ISSUE TITLE
bug: Pre-provisioned e2e maxShares failure test case hangs indefinitely

### ISSUE THREAD

**Issue by edreed** [abhisheksinghbaghel/azuredisk-csi-driver#215]
**What happened**:

The e2e test case "should fail when maxShares is invalid" hangs indefinitely causing the e2e test to timeout after 6 hours.

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

The root cause appears to be an attempt to update the state of the `AzVolume` instance from stale state.

The test case log produces the following output and hangs:
```log
I1006 11:27:49.308744   27052 azuredisk_driver.go:56] Using azure disk driver: disk.csi.azure.com
W1006 11:27:49.308848   27052 azure_disk_utils.go:333] maxShares cannot be set smaller than 1... Defaulting current maxShares (0) value to 1
I1006 11:27:49.308874   27052 crdprovisioner.go:213] Creating a new AzVolume CRI (invalid-max-shares)...
I1006 11:27:49.338907   27052 crdprovisioner.go:243] Successfully created AzVolume CRI (invalid-max-shares)...
```

Looking at the `AzVolume` controller logs we see:
```log
I1006 18:27:49.126681       1 util.go:51] azure_disk_utils.go:436] Initiating update with retry for *v1alpha1.AzVolume (invalid-max-shares)
I1006 18:27:49.133192       1 azvolume.go:151] Creating Volume (invalid-max-shares)...
E1006 18:27:49.133261       1 azvolume.go:158] failed to create volume invalid-max-shares: rpc error: code = InvalidArgument desc = parse 0 returned with invalid value: 0
I1006 18:27:49.133325       1 util.go:51] azure_disk_utils.go:436] Initiating update with retry for *v1alpha1.AzVolume (invalid-max-shares)
E1006 18:27:49.133359       1 azvolume.go:179] failed to update AzVolume (invalid-max-shares) with volume creation result (response: <nil>, error: rpc error: code = FailedPrecondition desc = azVolume's state 'Pending' cannot be updated to CreationFailed. Pending can only be updated to Creating, Deleting)
```

The first entry in the `AzVolume` controller log appears to be from a successful attempt to update the `AzVolume` state from `Pending` to `Creating`. Inspecting the state afterward, we can see that the update was successfuly.

```console
$ kubectl get azvolume -n azure-disk-csi invalid-max-shares --output=yaml
apiVersion: disk.csi.azure.com/v1alpha1
kind: AzVolume
metadata:
  creationTimestamp: "2021-10-06T18:27:49Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp:
  finalizers:
  - disk.csi.azure.com/azvolume-finalizer
  generation: 3
  name: invalid-max-shares
  namespace: azure-disk-csi
  resourceVersion: "24139"
  selfLink: /apis/disk.csi.azure.com/v1alpha1/namespaces/azure-disk-csi/azvolumes/invalid-max-shares
  uid: 8f40cd03-e0d7-4da2-8086-6607dd50aba4
spec:
  accessibilityRequirements: {}
  capacityRange:
    limit_bytes: 274877906944
    required_bytes: 274877906944
  contentVolumeSource:
    content_source: 0
    content_source_id: ""
  maxMountReplicaCount: 0
  parameters:
    maxShares: "0"
  underlyingVolume: invalid-max-shares
  volumeCapability:
  - access_details:
      access_type: 1
      fs_type: ""
    access_mode: 1
status:
  state: Creating
```

After receiving an invalid argument error from the attempt to create the volume, the `AzVolume` controller then tries to update the state to `CreationFailed` but cannot because it sees an earlier version of the object in the `Pending` state. The `CrdProvisioner` never sees the error and hangs indefinitely because the pre-provisioned e2e tests supply a context without a deadline.

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by edreed** [comment]
@sunpa93 Any ideas on how to fix this one?

**Comment by sunpa93** [comment]
> @sunpa93 Any ideas on how to fix this one?

This means that we can end up with similar failures in any update functions with `updateState` as it is inevitable that we might be trying to update an older version of the resource with an outdated state, especially given that we are getting objects from the cached reader. 

The hanging problem can likely arise whenever the object is stuck in `~ing` state. That said, in other `updateState` calls, I don't think this will be a concern because requeued reconciliation will be able to handle them but for the update routines after `CreateVolume`, `DeleteVolume`, `ExpandVolume`, `AttachVolume`, `DetachVolume`, we might end up with a similar hanging situation.

Maybe, we can add a `forceUpdateState` function that ignores the current state of the object to be used for those specific update sequences. As far as I can think, it should be guaranteed that the object is in a `~ing` state if it has reached these update sequences so I think we can safely force update the states in these cases.

**Comment by sunpa93** [comment]
> > Maybe, we can add a `forceUpdateState` function that ignores the current state of the object to be used for those specific update sequences. As far as I can think, it should be guaranteed that the object is in a `~ing` state if it has reached these update sequences so I think we can safely force update the states in these cases.
> 
> What about allowing a transition from the `Pending` state to `XXXFailed` states?

In that case, we should allow transition from `Pending` to `Created / Attached` states, and from `Created / Attached` states to `Deletion / DetachFailed` states although these cases seem improbable given that the reason we are seeing this error for this specific test is that `CreateVolume` function returned instantly due to wrong parameter, hence not allowing enough time for the cached reader to sync.
