### ISSUE TITLE
bug: Cloud provider fails to delete a disk because disk is still attached to a node

### ISSUE THREAD

**Issue by landreasyan** [abhisheksinghbaghel/azuredisk-csi-driver#255]
**What happened**:
Disk deletion sometimes fails because disk is still attached to a node. I have mostly observed this in pre-provisioning tests. Seems like cloud provider sometimes reports a success for detach requests when detach was not actually successful. This needs further investigation. 

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by sunpa93** [comment]
This issue seems to be caused not by an issue of `cloud-provider-azure` but a regression from adding controller support for pre-provisioned volume.

When PV controller deletes `AzVolume` CRI for pre-provisioned volume, it triggers `AzVolumeAttachment` clean up in `deleteCRIOnly` mode. And if this clean up comes before `ControllerUnpublishVolume`, which it often does when cleaning up pod and volume in our e2e pre-provisioned test cases, `AzVolumeAttachment` gets leaked (CRI gets deleted without underlying detachment). And from this point, the disk cannot be deleted until user manually detaches the volume.
